table dim_tournaments
	lineageTag: aade0e63-3601-443b-a3b7-6e173a8169a6

	column TOURNEY_ID
		dataType: string
		lineageTag: 02a292df-56bd-4994-b150-74a90d4af89a
		summarizeBy: none
		sourceColumn: TOURNEY_ID

		annotation SummarizationSetBy = Automatic

	column TOURNEY_NAME
		dataType: string
		lineageTag: 236f8341-544b-4801-ba90-e5bf681a506d
		summarizeBy: none
		sourceColumn: TOURNEY_NAME

		annotation SummarizationSetBy = Automatic

	column TOURNEY_LEVEL
		dataType: string
		lineageTag: 2be9d8b8-0d76-4504-988a-95eee59c1b61
		summarizeBy: none
		sourceColumn: TOURNEY_LEVEL

		annotation SummarizationSetBy = Automatic

	column TOURNEY_DRAW_SIZE
		dataType: int64
		formatString: 0
		lineageTag: eef719fb-2fcf-4c03-a738-e2e4c5fb0445
		summarizeBy: sum
		sourceColumn: TOURNEY_DRAW_SIZE

		annotation SummarizationSetBy = Automatic

	column TOURNEY_SURFACE
		dataType: string
		lineageTag: 1d29de63-6d20-4456-91ff-39c795ebf279
		summarizeBy: none
		sourceColumn: TOURNEY_SURFACE

		annotation SummarizationSetBy = Automatic

	column TOURNEY_IS_INDOOR
		dataType: string
		lineageTag: 99f9f64b-ec4b-4b0b-b29b-6d2fbefb5f8f
		summarizeBy: none
		sourceColumn: TOURNEY_IS_INDOOR

		annotation SummarizationSetBy = Automatic

	column TOURNEY_STATUS
		dataType: string
		lineageTag: dd00eca4-8a71-4928-b9c3-b11d323a84f7
		summarizeBy: none
		sourceColumn: TOURNEY_STATUS

		annotation SummarizationSetBy = Automatic

	column TOURNEY_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: a27d0b7f-1044-41a7-806f-6a9534893f07
		summarizeBy: none
		sourceColumn: TOURNEY_START_DATE

		variation Variation
			isDefault
			relationship: e414f4e9-9e1a-44f3-af77-cf713eac0a77
			defaultHierarchy: LocalDateTable_5c470835-ee6d-4a5b-adc5-94f477a1b9c6.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column REF_YEAR
		dataType: int64
		formatString: 0
		lineageTag: d71b251f-c3d8-4672-a351-96a9ae1fb6a5
		summarizeBy: sum
		sourceColumn: REF_YEAR

		annotation SummarizationSetBy = Automatic

	column SK_TOURNEY
		dataType: int64
		formatString: 0
		lineageTag: 61c2bc7e-12dd-4632-8334-d4c30138395c
		summarizeBy: none
		sourceColumn: SK_TOURNEY

		annotation SummarizationSetBy = Automatic

	partition dim_tournaments = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\phrug\OneDrive\Documentos\Repositórios\tennis-data-analytics\data\gold\dimension\dim_tournaments.csv"),[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"TOURNEY_ID", type text}, {"TOURNEY_NAME", type text}, {"TOURNEY_LEVEL", type text}, {"TOURNEY_DRAW_SIZE", Int64.Type}, {"TOURNEY_SURFACE", type text}, {"TOURNEY_IS_INDOOR", type text}, {"TOURNEY_STATUS", type text}, {"TOURNEY_START_DATE", type date}, {"REF_YEAR", Int64.Type}, {"SK_TOURNEY", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

