table fact_player_tournament_stats
	lineageTag: d95affcc-2dc0-407d-b626-fee0845bb5ac

	column SK_PLAYER
		dataType: int64
		formatString: 0
		lineageTag: 00749654-c87d-4cdc-adab-5445f0e34a63
		summarizeBy: none
		sourceColumn: SK_PLAYER

		annotation SummarizationSetBy = Automatic

	column SK_TOURNEY
		dataType: int64
		formatString: 0
		lineageTag: 3c855764-38b9-48ae-9a83-3cd0fc87e098
		summarizeBy: none
		sourceColumn: SK_TOURNEY

		annotation SummarizationSetBy = Automatic

	column SK_ENTRY_TYPE
		dataType: int64
		formatString: 0
		lineageTag: e5a70438-13db-4e3a-b90a-a9d87b95025a
		summarizeBy: none
		sourceColumn: SK_ENTRY_TYPE

		annotation SummarizationSetBy = Automatic

	column PLAYER_SEED
		dataType: int64
		formatString: 0
		lineageTag: b495f4c1-c42c-49c3-9c75-022a53387e4c
		summarizeBy: sum
		sourceColumn: PLAYER_SEED

		annotation SummarizationSetBy = Automatic

	column PLAYER_RANK_PTS
		dataType: int64
		formatString: 0
		lineageTag: e9da8406-d06a-4318-ad3b-c79c8e13fbd5
		summarizeBy: sum
		sourceColumn: PLAYER_RANK_PTS

		annotation SummarizationSetBy = Automatic

	column PLAYER_RANK
		dataType: int64
		formatString: 0
		lineageTag: c6be3fe7-1e31-4b06-ae69-987bd4571d20
		summarizeBy: sum
		sourceColumn: PLAYER_RANK

		annotation SummarizationSetBy = Automatic

	column IS_CHAMPION
		dataType: int64
		formatString: 0
		lineageTag: d7096429-e7e1-4a94-8f22-66b2156990d0
		summarizeBy: sum
		sourceColumn: IS_CHAMPION

		annotation SummarizationSetBy = Automatic

	column LAST_ROUND_PLAYED
		dataType: string
		lineageTag: 291d9d2a-6695-420c-9a3f-37253ba186f3
		summarizeBy: none
		sourceColumn: LAST_ROUND_PLAYED

		annotation SummarizationSetBy = Automatic

	column TOTAL_MATCHES
		dataType: int64
		formatString: 0
		lineageTag: 375dbcd8-0f27-4a1a-8caa-1873cfc765f4
		summarizeBy: sum
		sourceColumn: TOTAL_MATCHES

		annotation SummarizationSetBy = Automatic

	column TOTAL_MIN_IN_GAME
		dataType: int64
		formatString: 0
		lineageTag: 9c28e432-55e8-4835-9acb-0184941760ff
		summarizeBy: sum
		sourceColumn: TOTAL_MIN_IN_GAME

		annotation SummarizationSetBy = Automatic

	column LONGEST_MATCH
		dataType: int64
		formatString: 0
		lineageTag: 38715871-4c84-45fd-84c4-e6c1b53e66c1
		summarizeBy: sum
		sourceColumn: LONGEST_MATCH

		annotation SummarizationSetBy = Automatic

	column TOTAL_ACES
		dataType: int64
		formatString: 0
		lineageTag: c0912b91-9296-4ac0-bcac-c76b82614fda
		summarizeBy: sum
		sourceColumn: TOTAL_ACES

		annotation SummarizationSetBy = Automatic

	column TOTAL_DB_FAULTS
		dataType: int64
		formatString: 0
		lineageTag: 934e926d-0173-4622-9ad4-e02f385b1686
		summarizeBy: sum
		sourceColumn: TOTAL_DB_FAULTS

		annotation SummarizationSetBy = Automatic

	column TOTAL_SERVE_PTS
		dataType: int64
		formatString: 0
		lineageTag: a7424b11-5c67-4916-8e22-fee053784140
		summarizeBy: sum
		sourceColumn: TOTAL_SERVE_PTS

		annotation SummarizationSetBy = Automatic

	column TOTAL_1ST_SERVES_IN
		dataType: int64
		formatString: 0
		lineageTag: 5152aa05-919d-4863-9021-0c489f4b6aae
		summarizeBy: sum
		sourceColumn: TOTAL_1ST_SERVES_IN

		annotation SummarizationSetBy = Automatic

	column TOTAL_1ST_SERVE_PTS_WON
		dataType: int64
		formatString: 0
		lineageTag: 426b75ec-2f7c-4f56-8522-37ed38342faa
		summarizeBy: sum
		sourceColumn: TOTAL_1ST_SERVE_PTS_WON

		annotation SummarizationSetBy = Automatic

	column TOTAL_2ND_SERVE_PTS_WON
		dataType: int64
		formatString: 0
		lineageTag: 2383cc9c-2f7d-4336-b51e-252939e8edcc
		summarizeBy: sum
		sourceColumn: TOTAL_2ND_SERVE_PTS_WON

		annotation SummarizationSetBy = Automatic

	column TOTAL_SERVE_GAMES
		dataType: int64
		formatString: 0
		lineageTag: 908f27f1-a4bf-4a63-9488-c1dfa3e473a6
		summarizeBy: sum
		sourceColumn: TOTAL_SERVE_GAMES

		annotation SummarizationSetBy = Automatic

	column TOTAL_BP_SAVED
		dataType: int64
		formatString: 0
		lineageTag: 065c06b5-bd3c-40e9-9c85-dacf3f867202
		summarizeBy: sum
		sourceColumn: TOTAL_BP_SAVED

		annotation SummarizationSetBy = Automatic

	column TOTAL_BP_FACED
		dataType: int64
		formatString: 0
		lineageTag: fea5ce44-5cd0-4dad-937a-5a4bc8b4a6b8
		summarizeBy: sum
		sourceColumn: TOTAL_BP_FACED

		annotation SummarizationSetBy = Automatic

	partition fact_player_tournament_stats = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\phrug\OneDrive\Documentos\Repositórios\tennis-data-analytics\data\gold\fact\fact_player_tournament_stats.csv"),[Delimiter=",", Columns=20, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"SK_PLAYER", Int64.Type}, {"SK_TOURNEY", Int64.Type}, {"SK_ENTRY_TYPE", Int64.Type}, {"PLAYER_SEED", Int64.Type}, {"PLAYER_RANK_PTS", Int64.Type}, {"PLAYER_RANK", Int64.Type}, {"IS_CHAMPION", Int64.Type}, {"LAST_ROUND_PLAYED", type text}, {"TOTAL_MATCHES", Int64.Type}, {"TOTAL_MIN_IN_GAME", Int64.Type}, {"LONGEST_MATCH", Int64.Type}, {"TOTAL_ACES", Int64.Type}, {"TOTAL_DB_FAULTS", Int64.Type}, {"TOTAL_SERVE_PTS", Int64.Type}, {"TOTAL_1ST_SERVES_IN", Int64.Type}, {"TOTAL_1ST_SERVE_PTS_WON", Int64.Type}, {"TOTAL_2ND_SERVE_PTS_WON", Int64.Type}, {"TOTAL_SERVE_GAMES", Int64.Type}, {"TOTAL_BP_SAVED", Int64.Type}, {"TOTAL_BP_FACED", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

