table fact_player_head_to_head
	lineageTag: ba9e3e62-6b00-4bc4-bd5f-ad22c031519d

	column SK_PLAYER
		dataType: int64
		formatString: 0
		lineageTag: 9b15c0e8-a94f-405a-8727-7bf595477980
		summarizeBy: none
		sourceColumn: SK_PLAYER

		annotation SummarizationSetBy = Automatic

	column SK_PLAYER_OPPONENT
		dataType: int64
		formatString: 0
		lineageTag: 38b89079-0dd3-4a95-8325-23cb33946dfe
		summarizeBy: sum
		sourceColumn: SK_PLAYER_OPPONENT

		annotation SummarizationSetBy = Automatic

	column TOTAL_MATCHES
		dataType: int64
		formatString: 0
		lineageTag: 6f4d3a3a-48f9-43a3-b871-778524d40392
		summarizeBy: sum
		sourceColumn: TOTAL_MATCHES

		annotation SummarizationSetBy = Automatic

	column TOTAL_WINS
		dataType: int64
		formatString: 0
		lineageTag: 24aa5c76-d2a9-462f-9fa6-e3b2e77d9b15
		summarizeBy: sum
		sourceColumn: TOTAL_WINS

		annotation SummarizationSetBy = Automatic

	column TOTAL_LOSSES
		dataType: int64
		formatString: 0
		lineageTag: 995d32fc-59b4-43b5-9a15-546ebf472252
		summarizeBy: sum
		sourceColumn: TOTAL_LOSSES

		annotation SummarizationSetBy = Automatic

	partition fact_player_head_to_head = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\phrug\OneDrive\Documentos\Repositórios\tennis-data-analytics\data\gold\fact\fact_player_head_to_head.csv"),[Delimiter=",", Columns=5, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"SK_PLAYER", Int64.Type}, {"SK_PLAYER_OPPONENT", Int64.Type}, {"TOTAL_MATCHES", Int64.Type}, {"TOTAL_WINS", Int64.Type}, {"TOTAL_LOSSES", Int64.Type}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

