table fact_player_season
	lineageTag: d05c079c-a5d4-4d3a-9a54-195e2b659f14

	column SK_PLAYER
		dataType: int64
		formatString: 0
		lineageTag: c9a02c84-7b5a-4056-acf3-12417330fd95
		summarizeBy: none
		sourceColumn: SK_PLAYER

		annotation SummarizationSetBy = Automatic

	column REF_YEAR
		dataType: int64
		formatString: 0
		lineageTag: e3c87c09-bb4e-4381-b018-0d726ff797f8
		summarizeBy: sum
		sourceColumn: REF_YEAR

		annotation SummarizationSetBy = Automatic

	column TOTAL_MATCHES
		dataType: int64
		formatString: 0
		lineageTag: db0fcaa2-df5b-40bf-a294-9fc0f19c47cf
		summarizeBy: sum
		sourceColumn: TOTAL_MATCHES

		annotation SummarizationSetBy = Automatic

	column TOTAL_TOURNAMENTS
		dataType: int64
		formatString: 0
		lineageTag: 8a540178-1619-4353-af95-461b919007f7
		summarizeBy: sum
		sourceColumn: TOTAL_TOURNAMENTS

		annotation SummarizationSetBy = Automatic

	column TOTAL_WINS
		dataType: int64
		formatString: 0
		lineageTag: efeca4dc-3373-43ee-9fb4-30f60b056f2a
		summarizeBy: sum
		sourceColumn: TOTAL_WINS

		annotation SummarizationSetBy = Automatic

	column TOTAL_LOSSES
		dataType: int64
		formatString: 0
		lineageTag: 9e6663c3-48bf-453b-956a-ce93d183233b
		summarizeBy: sum
		sourceColumn: TOTAL_LOSSES

		annotation SummarizationSetBy = Automatic

	column TOTAL_TITLES
		dataType: int64
		formatString: 0
		lineageTag: dfb8d4af-3bdc-4f7f-91eb-30d2d0e63d6b
		summarizeBy: sum
		sourceColumn: TOTAL_TITLES

		annotation SummarizationSetBy = Automatic

	column AUS_OPEN_RESULT
		dataType: string
		lineageTag: 788cc52e-8b95-4a1e-b1b7-fd6b6d945b60
		summarizeBy: none
		sourceColumn: AUS_OPEN_RESULT

		annotation SummarizationSetBy = Automatic

	column ROLAND_GARROS_RESULT
		dataType: string
		lineageTag: b864fa67-1cda-4e61-863e-e17066d106ed
		summarizeBy: none
		sourceColumn: ROLAND_GARROS_RESULT

		annotation SummarizationSetBy = Automatic

	column WIMBLEDON_RESULT
		dataType: string
		lineageTag: d6142535-e1f4-474d-bd78-1aacc108df45
		summarizeBy: none
		sourceColumn: WIMBLEDON_RESULT

		annotation SummarizationSetBy = Automatic

	column US_OPEN_RESULT
		dataType: string
		lineageTag: 2da4580d-5f7c-4456-b640-b5a0f207a835
		summarizeBy: none
		sourceColumn: US_OPEN_RESULT

		annotation SummarizationSetBy = Automatic

	column PLAYER_START_RANK
		dataType: string
		lineageTag: 36a7d5b2-6b7c-4972-b8a1-f2fdbae98ecc
		summarizeBy: none
		sourceColumn: PLAYER_START_RANK

		annotation SummarizationSetBy = Automatic

	column PLAYER_FINAL_RANK
		dataType: string
		lineageTag: 3293064f-cc5d-4ef5-9124-815d514c3153
		summarizeBy: none
		sourceColumn: PLAYER_FINAL_RANK

		annotation SummarizationSetBy = Automatic

	column PLAYER_BEST_RANK
		dataType: string
		lineageTag: 0febbe11-0b90-4831-93ca-cce5b8067f20
		summarizeBy: none
		sourceColumn: PLAYER_BEST_RANK

		annotation SummarizationSetBy = Automatic

	column PLAYER_WORST_RANK
		dataType: string
		lineageTag: d08889c4-339c-457b-9dac-f6e75754115c
		summarizeBy: none
		sourceColumn: PLAYER_WORST_RANK

		annotation SummarizationSetBy = Automatic

	column PLAYER_START_RANK_PTS
		dataType: string
		lineageTag: 4ee4dd1c-cdee-4eaf-a0d8-fe68453aa9f2
		summarizeBy: none
		sourceColumn: PLAYER_START_RANK_PTS

		annotation SummarizationSetBy = Automatic

	column PLAYER_FINAL_RANK_PTS
		dataType: string
		lineageTag: 7fc545eb-353c-4a9d-82b4-8ba54724b831
		summarizeBy: none
		sourceColumn: PLAYER_FINAL_RANK_PTS

		annotation SummarizationSetBy = Automatic

	column PLAYER_BEST_RANK_PTS
		dataType: string
		lineageTag: a05ae462-9e1f-4adf-9f03-bedae622ecb1
		summarizeBy: none
		sourceColumn: PLAYER_BEST_RANK_PTS

		annotation SummarizationSetBy = Automatic

	column PLAYER_WORST_RANK_PTS
		dataType: string
		lineageTag: 5781b2d7-5020-4713-aac2-0a74eb4fb917
		summarizeBy: none
		sourceColumn: PLAYER_WORST_RANK_PTS

		annotation SummarizationSetBy = Automatic

	partition fact_player_season = m
		mode: import
		source =
				let
				    Fonte = Csv.Document(File.Contents("C:\Users\phrug\OneDrive\Documentos\Repositórios\tennis-data-analytics\data\gold\fact\fact_player_season.csv"),[Delimiter=",", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"SK_PLAYER", Int64.Type}, {"REF_YEAR", Int64.Type}, {"TOTAL_MATCHES", Int64.Type}, {"TOTAL_TOURNAMENTS", Int64.Type}, {"TOTAL_WINS", Int64.Type}, {"TOTAL_LOSSES", Int64.Type}, {"TOTAL_TITLES", Int64.Type}, {"AUS_OPEN_RESULT", type text}, {"ROLAND_GARROS_RESULT", type text}, {"WIMBLEDON_RESULT", type text}, {"US_OPEN_RESULT", type text}, {"PLAYER_START_RANK", type text}, {"PLAYER_FINAL_RANK", type text}, {"PLAYER_BEST_RANK", type text}, {"PLAYER_WORST_RANK", type text}, {"PLAYER_START_RANK_PTS", type text}, {"PLAYER_FINAL_RANK_PTS", type text}, {"PLAYER_BEST_RANK_PTS", type text}, {"PLAYER_WORST_RANK_PTS", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

