name: Deploy Airflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'dags/**'
      - 'bot/**'
      - 'src/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sync dags/
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VM_HOST }}
          REMOTE_USER: ${{ secrets.VM_USER }}
          SOURCE: "dags/"
          TARGET: "/home/opc/airflow/dags/"
          EXCLUDE: "/__pycache__/"

      - name: Sync bot/
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VM_HOST }}
          REMOTE_USER: ${{ secrets.VM_USER }}
          SOURCE: "bot/"
          TARGET: "/home/opc/airflow/bot/"
          EXCLUDE: "/__pycache__/"

      - name: Sync src/
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.VM_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.VM_HOST }}
          REMOTE_USER: ${{ secrets.VM_USER }}
          SOURCE: "src/"
          TARGET: "/home/opc/airflow/src/"
          EXCLUDE: "/__pycache__/"

# run sudo dnf install -y rsync || sudo yum install -y rsync at VM terminal